

// <auto-generated />
namespace CsvJoin.Models
{
    public class Csv1
    {
        public string Customer { get; set; }
        public string Product { get; set; }
        public string Price { get; set; }
        public string Quantity { get; set; }
    }
}
